from fpdf import FPDF
from datetime import datetime

def generate_pdf(topic: str, content: str) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Header bar ──
    pdf.set_fill_color(224, 123, 57)
    pdf.rect(0, 0, 210, 18, 'F')
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 4)
    pdf.cell(0, 10, "Study Buddy - Revision Sheet", ln=True)

    # ── Topic ──
    pdf.set_xy(10, 24)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(26, 25, 22)
    pdf.cell(0, 10, f"Topic: {topic}", ln=True)
    pdf.set_draw_color(226, 222, 214)
    pdf.line(10, 36, 200, 36)
    pdf.ln(6)

    # ── Sections ──
    icons = {
        "SIMPLE EXPLANATION": "EXPLANATION",
        "5-POINT SUMMARY": "SUMMARY",
        "PRACTICE QUESTIONS": "PRACTICE QUESTIONS",
        "DIFFICULTY RATING": "DIFFICULTY"
    }

    sections = content.split("##")
    for section in sections:
        if not section.strip():
            continue
        lines   = section.strip().split("\n", 1)
        heading = lines[0].strip()
        body    = lines[1].strip() if len(lines) > 1 else ""
        label   = icons.get(heading, heading)

        # Section heading
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(224, 123, 57)
        pdf.cell(0, 8, label, ln=True)

        # Section body
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(92, 90, 85)
        pdf.multi_cell(0, 6, body)
        pdf.ln(4)

    # ── Footer ──
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(155, 152, 144)
    date = datetime.now().strftime("%d %b %Y")
    pdf.cell(0, 8,
        f"Generated by Study Buddy · {date}",
        align="C"
    )

    return bytes(pdf.output())